In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\dell\Desktop\NEC\ShanghaiPM20100101_20151231.csv")
df.head()

No  year  month  day  hour  season  PM_Jingan  PM_US Post  PM_Xuhui  DEWP  \
0   1  2010      1    1     0       4        NaN         NaN       NaN  -6.0   
1   2  2010      1    1     1       4        NaN         NaN       NaN  -6.0   
2   3  2010      1    1     2       4        NaN         NaN       NaN  -7.0   
3   4  2010      1    1     3       4        NaN         NaN       NaN  -6.0   
4   5  2010      1    1     4       4        NaN         NaN       NaN  -6.0   

    HUMI    PRES  TEMP cbwd  Iws  precipitation  Iprec  
0  59.48  1026.1   1.0   cv  1.0            0.0    0.0  
1  59.48  1025.1   1.0   SE  2.0            0.0    0.0  
2  59.21  1025.1   0.0   SE  4.0            0.0    0.0  
3  63.94  1024.0   0.0   SE  5.0            0.0    0.0  
4  63.94  1023.0   0.0   SE  8.0            0.0    0.0

In [3]:
df.isnull().sum()

No                   0
year                 0
month                0
day                  0
hour                 0
season               0
PM_Jingan        27884
PM_US Post       18545
PM_Xuhui         27395
DEWP                13
HUMI                13
PRES                28
TEMP                13
cbwd                12
Iws                 12
precipitation     4009
Iprec             4009
dtype: int64

In [4]:
df.describe()

No          year         month           day          hour  \
count  52584.000000  52584.000000  52584.000000  52584.000000  52584.000000   
mean   26292.500000   2012.499772      6.523962     15.726609     11.500000   
std    15179.837614      1.707485      3.448452      8.798896      6.922252   
min        1.000000   2010.000000      1.000000      1.000000      0.000000   
25%    13146.750000   2011.000000      4.000000      8.000000      5.750000   
50%    26292.500000   2012.000000      7.000000     16.000000     11.500000   
75%    39438.250000   2014.000000     10.000000     23.000000     17.250000   
max    52584.000000   2015.000000     12.000000     31.000000     23.000000   

             season     PM_Jingan    PM_US Post      PM_Xuhui          DEWP  \
count  52584.000000  24700.000000  34039.000000  25189.000000  52571.000000   
mean       2.491100     57.395992     52.910544     57.678987     11.295372   
std        1.116988     47.616179     42.576138     48.412620      9.877649   
min        1.000000      1.000000      1.000000      1.000000    -21.000000   
25%        1.000000     26.000000     26.000000     26.000000      3.000000   
50%        2.000000     44.000000     41.000000     43.000000     12.000000   
75%        3.000000     73.000000     67.000000     73.000000     20.000000   
max        4.000000    635.000000    730.000000    636.000000     28.000000   

               HUMI          PRES          TEMP           Iws  precipitation  \
count  52571.000000  52556.000000  52571.000000  52572.000000   48575.000000   
mean      69.545646   1016.017564     17.471115     49.602367       0.142001   
std       17.658942      9.016829      9.315528     78.283572       1.065094   
min       11.320000    990.000000     -5.000000      0.000000       0.000000   
25%       57.930000   1008.100000     10.000000      6.000000       0.000000   
50%       72.420000   1016.000000     18.000000     20.000000       0.000000   
75%       83.370000   1023.000000     25.000000     61.000000       0.000000   
max      100.000000   1040.000000     41.000000   1110.000000      61.600000   

              Iprec  
count  48575.000000  
mean       0.935362  
std        6.586855  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max      226.400000

In [5]:
df.count()

No               52584
year             52584
month            52584
day              52584
hour             52584
season           52584
PM_Jingan        24700
PM_US Post       34039
PM_Xuhui         25189
DEWP             52571
HUMI             52571
PRES             52556
TEMP             52571
cbwd             52572
Iws              52572
precipitation    48575
Iprec            48575
dtype: int64

In [6]:
df.columns

Index(['No', 'year', 'month', 'day', 'hour', 'season', 'PM_Jingan',
       'PM_US Post', 'PM_Xuhui', 'DEWP', 'HUMI', 'PRES', 'TEMP', 'cbwd', 'Iws',
       'precipitation', 'Iprec'],
      dtype='object')

In [10]:
df1=df.drop(['No','year','month','day','hour','season','HUMI','PRES','Iws','precipitation','PM_Xuhui','PM_Jingan','PM_US Post','cbwd','Iprec'],axis = 1)
df1.head()

DEWP  TEMP
0  -6.0   1.0
1  -6.0   1.0
2  -7.0   0.0
3  -6.0   0.0
4  -6.0   0.0

In [11]:
df1.shape

(52584, 2)

In [12]:
df2=df1.dropna(axis = 0)
df2.head()

DEWP  TEMP
0  -6.0   1.0
1  -6.0   1.0
2  -7.0   0.0
3  -6.0   0.0
4  -6.0   0.0

In [13]:
df2.isnull().sum()

DEWP    0
TEMP    0
dtype: int64

In [14]:
df3 = (df2-df2.min())/(df2.max()-df2.min())
df3.head()

DEWP      TEMP
0  0.306122  0.130435
1  0.306122  0.130435
2  0.285714  0.108696
3  0.306122  0.108696
4  0.306122  0.108696

In [15]:
df_n= df3.select_dtypes(include = [np.number])
df_l = df_n.loc[:,['DEWP','TEMP']]
df_l.head()

DEWP      TEMP
0  0.306122  0.130435
1  0.306122  0.130435
2  0.285714  0.108696
3  0.306122  0.108696
4  0.306122  0.108696

In [16]:
df_l.shape

(52571, 2)

In [18]:
x = np.array(df_l['DEWP']).reshape(52571,1)
y = np.array(df_l['TEMP']).reshape(52571,1)
x.shape
y.shape

(52571, 1)

In [19]:
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model

In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.20)
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(42056, 1) (42056, 1)
(10515, 1) (10515, 1)


In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
reg = LinearRegression()
reg.fit(X_train , Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
reg.coef_

array([[0.89451228]])

In [24]:
reg.intercept_

array([-0.10088256])

In [25]:
Y_prediction = reg.predict(X_test)
Y_prediction

array([[0.3007352 ],
       [0.61107619],
       [0.20945843],
       ...,
       [0.61107619],
       [0.41026731],
       [0.72060831]])

In [26]:
a = pd.DataFrame({"actual":list(Y_test),"prediction":list(Y_prediction)})
a.head()

actual             prediction
0   [0.2391304347826087]  [0.30073519577020685]
1   [0.6086956521739131]   [0.6110761924881185]
2  [0.13043478260869565]  [0.20945843202964454]
3  [0.45652173913043476]   [0.5380547814956689]
4  [0.32608695652173914]   [0.3189905485183193]